// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX9oKjiUnVbPKDpEVpncfCxd-2ASbzpas',
    appId: '1:189280957769:web:3f85e8f241151fbe499698',
    messagingSenderId: '189280957769',
    projectId: 'motobox-firestore',
    authDomain: 'motobox-firestore.firebaseapp.com',
    storageBucket: 'motobox-firestore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ7KibMTtuFzqZ11iwVnGIXitH-PlmoGI',
    appId: '1:189280957769:android:4ee27fe52d4ae60e499698',
    messagingSenderId: '189280957769',
    projectId: 'motobox-firestore',
    storageBucket: 'motobox-firestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqFrz3veZ3_SIACcA6Umik1lzSta0Rj9o',
    appId: '1:189280957769:ios:9a8862642a2a2eea499698',
    messagingSenderId: '189280957769',
    projectId: 'motobox-firestore',
    storageBucket: 'motobox-firestore.appspot.com',
    iosClientId: '189280957769-45to2uup5vsqdgsbh98rq22na9inpaqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.motobox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqFrz3veZ3_SIACcA6Umik1lzSta0Rj9o',
    appId: '1:189280957769:ios:07e8cc0accaaa579499698',
    messagingSenderId: '189280957769',
    projectId: 'motobox-firestore',
    storageBucket: 'motobox-firestore.appspot.com',
    iosClientId: '189280957769-7kb6p2adbicflnnlq7iba02h1ukv1ugn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealsApp',
  );
}
